### PR TITLE
Replacing CSVW git dependency with npm version. 

### PR DESCRIPTION
**Pull request by ktk**
The XSLX parser is still git but points to the current branch. One test fails in a deep equal but the same happens for master so it does not look like I introduced that.

Once the XSLT branch is merged we need to point to master again there.

### CODE REVIEW

**Comment by bergos** [comment]
Was the XSLT parser used in any of the old pipelines? If not I would just remove it.

**Comment by bergos** [comment]
XSLT master works again

**Comment by ktk** [comment]
Great will check. Yes in SSZ we used it, that's the one I need to get to work again for the moment.

**Comment by ktk** [comment]
Ok the deep equal still fails obviously but I propose we merge like this. I also added a paragraph in the README that says it should not be used anymore.

**Review by bergos — APPROVED** [review]

**Pull request merged**
